### ISSUE TITLE
Allow flexible removal of individual components in advanced search

### ISSUE THREAD

**Issue by High3eam** [HandyMenny/uecapabilityparser-web#198]
When adding components to advanced search and then I want to remove a specific component that is not the last one, I have to remove all components from the list until I reach the one I was actually going to remove.
It would be great if it was possible to remove individual and specific components from the list.
For example by adding a removal button next to the component but I am open to other ideas as well:
![advanced-search](https://github.com/HandyMenny/uecapabilityparser-web/assets/15855905/84f91113-8197-466d-befa-42284d4cf208)

**Comment by HandyMenny** [comment]
I was also thinking of adding +/- buttons in the same row of the component, mainly to reduce wasted space
